# Please create S3 credentials secret before deploying this application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-api
  namespace: baas
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: baas-api-sa
      containers:
        - name: baas-api
          image: ghcr.io/wkebaas/api:v0.1.12
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: baas-s3-credentials
            - configMapRef:
                name: baas-api-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: baas-db-app
                  key: uri
