apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baas-api-ingress
  namespace: baas
spec:
  entryPoints:
    - websecure
  routes:
    # You can comment this rule for disabling OpenAPI spec access
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && Path(`/api/openapi.yaml`)
      kind: Rule
      services:
        - name: baas-api
          port: 3000
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: baas-api
          port: 3000
      middlewares:
        - name: baas-api-strip-prefix
  tls:
    secretName: wke-tls
