apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baas

resources:
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  # - ingress.yaml
  - role.yaml
  - role-binding.yaml
  - service-account.yaml

secretGenerator:
  - name: baas-s3-credentials
    envs:
      - secret.env

configMapGenerator:
  - name: baas-api-config
    envs:
      - config.env

labels:
  - pairs:
      app: baas-api
    includeSelectors: true
