apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baas-web-ingress
  namespace: baas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`baas.wke.csie.ncnu.edu.tw`)
      kind: Rule
      services:
        - name: baas-web
          port: 3000
  tls:
    secretName: wke-tls
