apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baas

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: baas-web-config
    envs:
      - config.env

labels:
  - pairs:
      app: baas-web
    includeSelectors: true
