apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baas-pgrst-ingress
  namespace: baas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && PathPrefix(`/api/rest/docs/`)
      kind: Rule
      services:
        - name: baas-pgrst
          port: 8080
      middlewares:
        - name: baas-pgrst-strip-prefix
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && PathPrefix(`/api/rest`)
      kind: Rule
      services:
        - name: baas-pgrst
          port: 3000
      middlewares:
        - name: baas-pgrst-strip-prefix
  tls:
    secretName: wke-tls
