apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baas

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - middleware.yaml

secretGenerator:
  - name: baas-pgrst-secret
    envs:
      - secret.env

configMapGenerator:
  - name: baas-pgrst-config
    envs:
      - config.env

labels:
  - pairs:
      app: baas-pgrst
    includeSelectors: true
