apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baas-auth-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && PathPrefix(`/api/auth`)
      kind: Rule
      services:
        - name: baas-auth
          port: 3000
  tls:
    secretName: wke-tls
