apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: baas-db-ingress
  namespace: baas
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`db.baas.wke.csie.ncnu.edu.tw`)
      services:
        - name: baas-db-rw
          port: 5432
  tls:
    secretName: baas-wildcard-tls
