apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: baas

resources:
  - db-cluster.yaml
  - database.yaml
  - ingress.yaml

secretGenerator:
  - name: baas-db-authenticator
    envs:
      - authenticator.secret.env

generatorOptions:
  disableNameSuffixHash: true
