apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-catalog
  - db-cluster
  - migrate-baas
  - baas-auth
  - baas-pgrst
  - project-middlewares
  - baas-api
  - baas-web
